# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bf_15', models.IntegerField(verbose_name='\u6536\u5165\uff082015\u5e74\uff09')),
                ('bf_16', models.IntegerField(verbose_name='\u6536\u5165\uff082016\u5e74\uff09')),
                ('bf_17', models.IntegerField(verbose_name='\u6536\u5165\uff082017\u5e74\uff09')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
        ),
    ]
